<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.qa.hubspot.tests.HomePageTest" tests="1" time="5.045" ignored="5" failures="0" timestamp="11 Feb 2020 08:12:50 GMT" skipped="0" hostname="Naveen-Mac.local" errors="1">
  <testcase name="verifyHomePageTitleTest" time="5.045" classname="com.qa.hubspot.tests.HomePageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.qa.hubspot.tests.HomePageTest.verifyHomePageTitleTest(HomePageTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- verifyHomePageTitleTest -->
  <testcase name="verifyLoggedInUserTest" classname="com.qa.hubspot.tests.HomePageTest">
    <skipped/>
  </testcase> <!-- verifyLoggedInUserTest -->
  <testcase name="verifyHomePageHeaderTest" classname="com.qa.hubspot.tests.HomePageTest">
    <skipped/>
  </testcase> <!-- verifyHomePageHeaderTest -->
  <testcase name="verifyLoginPageTitleTest" classname="com.qa.hubspot.tests.LoginPageTest">
    <skipped/>
  </testcase> <!-- verifyLoginPageTitleTest -->
  <testcase name="loginTest" classname="com.qa.hubspot.tests.LoginPageTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="login_InvalidTestCases" classname="com.qa.hubspot.tests.LoginPageTest">
    <skipped/>
  </testcase> <!-- login_InvalidTestCases -->
</testsuite> <!-- com.qa.hubspot.tests.HomePageTest -->
